// SPDX-License-Identifier: Apache-2.0

// Command generate-agent-mcp-client renders policy-free TypeScript transport
// constants from the engine-owned scoped MCP contract.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/mcuadros/director-engine/domain/agentbridge"
	domainconfig "github.com/mcuadros/director-engine/domain/configuration"
)

func render(schema []byte) ([]byte, error) {
	definition, err := agentbridge.ParseDefinition(schema)
	if err != nil {
		return nil, err
	}
	hash, err := agentbridge.CanonicalSHA256(schema)
	if err != nil {
		return nil, err
	}
	var output strings.Builder
	output.WriteString("// SPDX-License-Identifier: Apache-2.0\n")
	output.WriteString("// Code generated by Director Engine. DO NOT EDIT.\n\n")
	output.WriteString("// Transport facts only; authorization remains in the Go engine.\n\n")
	fmt.Fprintf(&output, "export const AGENT_MCP_CONTRACT_VERSION = %s as const;\n", strconv.Quote(definition.ContractVersion))
	fmt.Fprintf(&output, "export const AGENT_MCP_CONTRACT_SHA256 = %s as const;\n", strconv.Quote(hash))
	fmt.Fprintf(&output, "export const AGENT_MCP_SUPPORTED_PASEO = %s as const;\n", strconv.Quote(definition.SupportedPaseo))
	fmt.Fprintf(&output, "export const AGENT_MCP_MAXIMUM_REQUEST_BYTES = %d as const;\n", definition.MaximumRequestBytes)
	fmt.Fprintf(&output, "export const AGENT_MCP_MAXIMUM_RESPONSE_BYTES = %d as const;\n", definition.MaximumResponseBytes)
	output.WriteString("export const AGENT_MCP_ROLES = [\n")
	for _, role := range definition.Roles {
		fmt.Fprintf(&output, "  %s,\n", strconv.Quote(string(role)))
	}
	output.WriteString("] as const;\n")
	output.WriteString("export const AGENT_MCP_CAPABILITIES = [\n")
	for _, capability := range definition.Capabilities {
		fmt.Fprintf(&output, "  %s,\n", strconv.Quote(string(capability)))
	}
	output.WriteString("] as const;\n")
	output.WriteString("export const AGENT_MCP_PROVIDER_CLI_VERSIONS = {\n")
	providers := make([]domainconfig.Provider, 0, len(definition.ProviderCLIVersions))
	for provider := range definition.ProviderCLIVersions {
		providers = append(providers, provider)
	}
	sort.Slice(providers, func(left, right int) bool { return providers[left] < providers[right] })
	for _, provider := range providers {
		fmt.Fprintf(&output, "  %s: %s,\n", strconv.Quote(string(provider)), strconv.Quote(definition.ProviderCLIVersions[provider]))
	}
	output.WriteString("} as const;\n\n")
	output.WriteString("export const AGENT_MCP_TOOLS = [\n")
	for _, tool := range definition.Tools {
		canonicalSchema, err := agentbridge.CanonicalJSON(tool.InputSchema)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&output, "  { name: %s, description: %s, capability: %s, roles: [", strconv.Quote(tool.Name), strconv.Quote(tool.Description), strconv.Quote(string(tool.Capability)))
		for index, role := range tool.Roles {
			if index > 0 {
				output.WriteString(", ")
			}
			output.WriteString(strconv.Quote(string(role)))
		}
		fmt.Fprintf(&output, "] as const, mutating: %t, inputSchema: %s as const },\n", tool.Mutating, canonicalSchema)
	}
	output.WriteString("] as const;\n\n")
	output.WriteString(`export type AgentMCPRole = (typeof AGENT_MCP_ROLES)[number];
export type AgentMCPCapability = (typeof AGENT_MCP_CAPABILITIES)[number];
export type AgentMCPProvider = keyof typeof AGENT_MCP_PROVIDER_CLI_VERSIONS;
export type AgentMCPToolName = (typeof AGENT_MCP_TOOLS)[number]["name"];

export interface AgentMCPProviderObservation {
  schemaVersion: 1;
  contractVersion: typeof AGENT_MCP_CONTRACT_VERSION;
  contractHash: typeof AGENT_MCP_CONTRACT_SHA256;
  discoveryRevision: string;
  paseoVersion: string;
  provider: AgentMCPProvider;
  cliVersion: string;
  state: "ready" | "unavailable";
  model: string;
  effort: string;
  mode: string;
  permissionMode: string;
  providerOptions: readonly Readonly<{ name: string; value: string }>[];
  mcpCapabilities: readonly AgentMCPCapability[];
  sessionStdioMcp: boolean;
  exactMcpToolPolicy: boolean;
  runtimeProbePassed: boolean;
}

export interface AgentMCPSessionLaunch {
  contractVersion: typeof AGENT_MCP_CONTRACT_VERSION;
  contractHash: typeof AGENT_MCP_CONTRACT_SHA256;
  sessionSha256: string;
  role: AgentMCPRole;
  provider: AgentMCPProvider;
  model: string;
  tools: readonly AgentMCPToolName[];
  server: Readonly<{
    name: string;
    command: string;
    args: readonly string[];
    env: Readonly<Record<string, string>>;
  }>;
}
`)
	return []byte(output.String()), nil
}

func run(arguments []string) error {
	flags := flag.NewFlagSet("generate-agent-mcp-client", flag.ContinueOnError)
	schemaPath := flags.String("schema", "domain/agentbridge/schemas/director-agent-mcp.v1.json", "engine-owned schema")
	outputPath := flags.String("output", "../generated/agent-mcp-contract.shared.ts", "generated TypeScript output")
	if err := flags.Parse(arguments); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("unexpected positional arguments")
	}
	schema, err := os.ReadFile(*schemaPath)
	if err != nil {
		return err
	}
	generated, err := render(schema)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(*outputPath, generated, 0o644)
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
