// SPDX-License-Identifier: Apache-2.0

// Command generate-project-admin-mcp-client renders transport-only TypeScript
// facts from the Engine-owned Project administration MCP schema.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/mcuadros/director-engine/domain/projectadmin"
)

func render(schema []byte) ([]byte, error) {
	definition, err := projectadmin.ParseDefinition(schema)
	if err != nil {
		return nil, err
	}
	hash, err := projectadmin.CanonicalSHA256(schema)
	if err != nil {
		return nil, err
	}
	var output strings.Builder
	output.WriteString("// SPDX-License-Identifier: Apache-2.0\n// Code generated by Director Engine. DO NOT EDIT.\n\n")
	output.WriteString("// Transport facts only; Project authority remains in the Go engine.\n\n")
	fmt.Fprintf(&output, "export const PROJECT_ADMIN_MCP_CONTRACT_VERSION = %s as const;\n", strconv.Quote(definition.ContractVersion))
	fmt.Fprintf(&output, "export const PROJECT_ADMIN_MCP_CONTRACT_SHA256 = %s as const;\n", strconv.Quote(hash))
	fmt.Fprintf(&output, "export const PROJECT_ADMIN_MCP_SUPPORTED_PASEO = %s as const;\n", strconv.Quote(definition.SupportedPaseo))
	fmt.Fprintf(&output, "export const PROJECT_ADMIN_MCP_MAXIMUM_REQUEST_BYTES = %d as const;\n", definition.MaximumRequestBytes)
	fmt.Fprintf(&output, "export const PROJECT_ADMIN_MCP_MAXIMUM_RESPONSE_BYTES = %d as const;\n", definition.MaximumResponseBytes)
	output.WriteString("export const PROJECT_ADMIN_MCP_TOOLS = [\n")
	for _, tool := range definition.Tools {
		input, err := projectadmin.CanonicalJSON(tool.InputSchema)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&output, "  { name: %s, description: %s, mutating: %t, inputSchema: %s as const },\n",
			strconv.Quote(tool.Name), strconv.Quote(tool.Description), tool.Mutating, input)
	}
	output.WriteString(`] as const;

export type ProjectAdminMCPToolName = (typeof PROJECT_ADMIN_MCP_TOOLS)[number]["name"];

export interface ProjectAdminMCPSessionLaunch {
  contractVersion: typeof PROJECT_ADMIN_MCP_CONTRACT_VERSION;
  contractHash: typeof PROJECT_ADMIN_MCP_CONTRACT_SHA256;
  sessionSha256: string;
  sessionId: string;
  audience: string;
  tools: readonly ProjectAdminMCPToolName[];
  server: Readonly<{
    name: "director-project-admin";
    command: string;
    args: readonly string[];
    env: Readonly<{ DIRECTOR_PROJECT_ADMIN_TOKEN: string }>;
  }>;
}
`)
	return []byte(output.String()), nil
}

func run(arguments []string) error {
	flags := flag.NewFlagSet("generate-project-admin-mcp-client", flag.ContinueOnError)
	schemaPath := flags.String("schema", "domain/projectadmin/schemas/director-project-admin-mcp.v1.json", "engine-owned schema")
	outputPath := flags.String("output", "../generated/project-admin-mcp-contract.shared.ts", "generated TypeScript output")
	if err := flags.Parse(arguments); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("unexpected positional arguments")
	}
	schema, err := os.ReadFile(*schemaPath)
	if err != nil {
		return err
	}
	generated, err := render(schema)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(*outputPath, generated, 0o644)
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
