#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0

import { spawnSync } from "node:child_process";
import {
  closeSync,
  constants,
  fsyncSync,
  openSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { auditDependencyClosure } from "../ci/dependency-audit.mjs";
import {
  RuntimeConfigurationError,
  assertRuntimeDeployment,
  loadRuntimeConfiguration,
} from "../../connector/runtime-configuration.server.mjs";

const SUPPORTED_PASEO_VERSION = "0.7.2";
const MINIMUM_NODE_MAJOR = 22;

function fail(code, message) {
  process.stderr.write(`${code}: ${message}\n`);
  return 1;
}

export function verifyInstall(options = {}) {
  const platform = options.platform ?? process.platform;
  const architecture = options.architecture ?? process.arch;
  const nodeVersion = options.nodeVersion ?? process.versions.node;
  if (platform !== "linux") {
    return { code: "DIRECTOR_INSTALL_PLATFORM_UNSUPPORTED", message: "Director 1.0 supports Linux only" };
  }
  if (architecture !== "x64") {
    return { code: "DIRECTOR_INSTALL_TARGET_UNSUPPORTED", message: "Director release target linux-amd64 is required" };
  }
  const nodeMajor = Number.parseInt(String(nodeVersion).split(".", 1)[0] ?? "", 10);
  if (!Number.isSafeInteger(nodeMajor) || nodeMajor < MINIMUM_NODE_MAJOR) {
    return { code: "DIRECTOR_INSTALL_NODE_UNSUPPORTED", message: `Node.js ${MINIMUM_NODE_MAJOR} or newer is required` };
  }
  const paseo = options.paseoVersion ?? (() => {
    const result = spawnSync("paseo", ["--version"], {
      encoding: "utf8",
      env: process.env.PATH ? { PATH: process.env.PATH } : {},
      shell: false,
      timeout: 10_000,
      maxBuffer: 16 * 1024,
    });
    return result.status !== 0 || (result.error && result.status === null) ? "unavailable" : result.stdout.trim();
  });
  const paseoVersion = String(typeof paseo === "function" ? paseo() : paseo).trim();
  if (paseoVersion !== SUPPORTED_PASEO_VERSION) {
    const observed = /^[0-9A-Za-z.+_-]{1,64}$/u.test(paseoVersion) ? paseoVersion : "unavailable";
    return {
      code: "DIRECTOR_INSTALL_PASEO_UNSUPPORTED",
      message: `Director supports exact Paseo ${SUPPORTED_PASEO_VERSION}; observed ${observed}`,
    };
  }
  const repositoryRoot = options.repositoryRoot ?? resolve(fileURLToPath(new URL("../..", import.meta.url)));
  const audit = auditDependencyClosure(repositoryRoot, { installed: true });
  if (audit.errors.length > 0) {
    return { code: "DIRECTOR_INSTALL_DEPENDENCY_AUDIT", message: audit.errors[0] };
  }
  return { code: "DIRECTOR_INSTALL_READY", message: `exact Paseo ${SUPPORTED_PASEO_VERSION}; dependency ${audit.sha256}` };
}

function git(repositoryRoot, args) {
  const result = spawnSync("git", ["-C", repositoryRoot, ...args], {
    encoding: "utf8",
    env: process.env.PATH
      ? { PATH: process.env.PATH, GIT_CONFIG_NOSYSTEM: "1" }
      : { GIT_CONFIG_NOSYSTEM: "1" },
    shell: false,
    timeout: 10_000,
    maxBuffer: 64 * 1024,
  });
  if (result.status !== 0 || (result.error && result.status === null)) {
    throw new Error("DIRECTOR_INSTALL_SOURCE_IDENTITY");
  }
  return result.stdout.trim();
}

export function preparedConnectorMetadataSource(connectorCommit, releaseMetadata) {
  if (!/^[0-9a-f]{40}$/u.test(connectorCommit)) {
    throw new Error("DIRECTOR_INSTALL_SOURCE_IDENTITY");
  }
  return [
    "// SPDX-License-Identifier: Apache-2.0",
    "// Generated by the declared Paseo candidate-preparation boundary; do not edit.",
    "",
    "export const INSTALLED_CONNECTOR_METADATA = " +
      JSON.stringify({
        schemaVersion: 1,
        state: "prepared",
        connectorCommit,
        releaseMetadata,
      }, null, 2) + " as const;",
    "",
  ].join("\n");
}

function writePreparedMetadata(repositoryRoot, source) {
  const relativePath = "connector/install-metadata.server.ts";
  const target = join(repositoryRoot, relativePath);
  const current = readFileSync(target, "utf8");
  const trackedStatus = git(repositoryRoot, ["status", "--porcelain=v1", "--untracked-files=no"]);
  const generatedOnly = /^(?:M|MM) connector\/install-metadata\.server\.ts$/u.test(trackedStatus);
  if (trackedStatus !== "" && !(generatedOnly && current === source)) {
    throw new Error("DIRECTOR_INSTALL_SOURCE_DIRTY");
  }
  if (current === source) return "adopted";
  const temporary = join(dirname(target), `.install-metadata-${process.pid}.tmp`);
  const descriptor = openSync(
    temporary,
    constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW,
    0o600,
  );
  try {
    writeFileSync(descriptor, source);
    fsyncSync(descriptor);
  } finally {
    closeSync(descriptor);
  }
  try {
    renameSync(temporary, target);
    const directory = openSync(dirname(target), constants.O_RDONLY | constants.O_DIRECTORY | constants.O_NOFOLLOW);
    try {
      fsyncSync(directory);
    } finally {
      closeSync(directory);
    }
  } finally {
    rmSync(temporary, { force: true });
  }
  return "generated";
}

export function prepareRuntimeInstallation(options = {}) {
  const repositoryRoot = options.repositoryRoot ?? resolve(fileURLToPath(new URL("../..", import.meta.url)));
  const environment = options.environment ?? process.env;
  const loaded = loadRuntimeConfiguration(environment, options.home);
  const configuration = assertRuntimeDeployment(repositoryRoot, loaded, environment);
  const connectorCommit = git(repositoryRoot, ["rev-parse", "HEAD"]);
  let releaseMetadata;
  try {
    releaseMetadata = JSON.parse(readFileSync(join(repositoryRoot, "release", "engine.json"), "utf8"));
  } catch {
    throw new Error("DIRECTOR_INSTALL_RELEASE_METADATA");
  }
  const state = writePreparedMetadata(
    repositoryRoot,
    preparedConnectorMetadataSource(connectorCommit, releaseMetadata),
  );
  return {
    code: "DIRECTOR_INSTALL_RUNTIME_READY",
    configurationSha256: configuration.diagnostics.sha256,
    legacyEnvironment: configuration.diagnostics.legacyEnvironment,
    metadataState: state,
    settings: configuration.diagnostics.settings,
  };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const result = verifyInstall();
  if (result.code !== "DIRECTOR_INSTALL_READY") {
    process.exitCode = fail(result.code, result.message);
  } else {
    try {
      const runtime = prepareRuntimeInstallation();
      process.stdout.write(`${result.code}: ${result.message}; ${JSON.stringify(runtime)}\n`);
    } catch (error) {
      const code = error instanceof RuntimeConfigurationError
        ? error.code
        : /^[A-Z0-9_]{3,96}$/u.test(error instanceof Error ? error.message : "")
          ? error.message
          : "DIRECTOR_INSTALL_RUNTIME_CONFIGURATION";
      process.exitCode = fail(code, "Director runtime preparation failed closed");
    }
  }
}
