// SPDX-License-Identifier: Apache-2.0

// Command generate-host-client produces the TypeScript client from the
// engine-owned host contract. It has no dependency on the Paseo host package.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/mcuadros/director-engine/contract"
)

func render(schema []byte) ([]byte, error) {
	definition, err := contract.ParseDefinition(schema)
	if err != nil {
		return nil, err
	}
	contractHash, err := contract.CanonicalSHA256(schema)
	if err != nil {
		return nil, err
	}
	var output strings.Builder
	output.WriteString("// SPDX-License-Identifier: Apache-2.0\n")
	output.WriteString("// Code generated by Director Engine. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "export const HOST_CONTRACT_VERSION = %s as const;\n", strconv.Quote(definition.ContractVersion))
	fmt.Fprintf(&output, "export const HOST_CONTRACT_SHA256 = %s as const;\n", strconv.Quote(contractHash))
	fmt.Fprintf(&output, "export const HOST_CREDENTIAL_SCOPE = %s as const;\n", strconv.Quote(definition.CredentialScope))
	output.WriteString("export const HOST_CAPABILITIES = [\n")
	for _, capability := range definition.Capabilities {
		fmt.Fprintf(&output, "  %s,\n", strconv.Quote(capability))
	}
	output.WriteString("] as const;\n\n")
	output.WriteString(`export type HostCapability = (typeof HOST_CAPABILITIES)[number];

export interface HostDescriptor {
  credentialScope: typeof HOST_CREDENTIAL_SCOPE;
  contractVersion: typeof HOST_CONTRACT_VERSION;
  contractHash: typeof HOST_CONTRACT_SHA256;
  capabilities: typeof HOST_CAPABILITIES;
}

export interface HostCommand {
  requestId: string;
  idempotencyKey: string;
  expectedVersion: number;
  capability: HostCapability;
  arguments: Readonly<Record<string, unknown>>;
}

export interface HostObservation {
  requestId: string;
  cursor: number;
  observedAt: string;
  result: unknown;
}

export interface DirectorHost {
  describe(): Promise<HostDescriptor>;
  invoke(command: HostCommand): Promise<HostObservation>;
}

export class HostHandshakeError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "HostHandshakeError";
    this.code = code;
  }
}

export const EXPECTED_HOST_DESCRIPTOR: HostDescriptor = Object.freeze({
  credentialScope: HOST_CREDENTIAL_SCOPE,
  contractVersion: HOST_CONTRACT_VERSION,
  contractHash: HOST_CONTRACT_SHA256,
  capabilities: HOST_CAPABILITIES,
});

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

export function assertHostDescriptor(value: unknown): HostDescriptor {
  if (!isRecord(value)) {
    throw new HostHandshakeError("HOST_DESCRIPTOR_REQUIRED", "host descriptor is required");
  }
  const keys = Object.keys(value).sort();
  const expectedKeys = ["capabilities", "contractHash", "contractVersion", "credentialScope"];
  if (keys.length !== expectedKeys.length || keys.some((key, index) => key !== expectedKeys[index])) {
    throw new HostHandshakeError("HOST_DESCRIPTOR_FIELDS", "host descriptor fields do not match");
  }
  if (value.credentialScope !== HOST_CREDENTIAL_SCOPE) {
    throw new HostHandshakeError("HOST_CREDENTIAL_SCOPE", "host credential scope does not match");
  }
  if (value.contractVersion !== HOST_CONTRACT_VERSION) {
    throw new HostHandshakeError("HOST_CONTRACT_VERSION", "host contract version does not match");
  }
  if (value.contractHash !== HOST_CONTRACT_SHA256) {
    throw new HostHandshakeError("HOST_CONTRACT_HASH", "host contract hash does not match");
  }
  if (!Array.isArray(value.capabilities)) {
    throw new HostHandshakeError("HOST_CAPABILITIES", "host capabilities are required");
  }
  if (
    value.capabilities.length !== HOST_CAPABILITIES.length ||
    value.capabilities.some((capability, index) => capability !== HOST_CAPABILITIES[index])
  ) {
    throw new HostHandshakeError("HOST_CAPABILITIES", "host capability set does not match");
  }
  return value as unknown as HostDescriptor;
}
`)
	return []byte(output.String()), nil
}

func run(arguments []string) error {
	flags := flag.NewFlagSet("generate-host-client", flag.ContinueOnError)
	schemaPath := flags.String("schema", "contract/host-interface.v1.json", "engine-owned schema path")
	outputPath := flags.String("output", "../shared/generated-host-contract.shared.ts", "generated TypeScript path")
	if err := flags.Parse(arguments); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return fmt.Errorf("unexpected arguments: %s", strings.Join(flags.Args(), " "))
	}
	schema, err := os.ReadFile(*schemaPath)
	if err != nil {
		return fmt.Errorf("read schema: %w", err)
	}
	generated, err := render(schema)
	if err != nil {
		return fmt.Errorf("generate client: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := os.WriteFile(*outputPath, generated, 0o644); err != nil {
		return fmt.Errorf("write client: %w", err)
	}
	return nil
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "generate-host-client: %v\n", err)
		os.Exit(1)
	}
}
