// SPDX-License-Identifier: Apache-2.0
// Code generated by Director Engine. DO NOT EDIT.

export const HOST_CONTRACT_VERSION = "director-host/v1" as const;
export const HOST_CONTRACT_SHA256 = "a0104959bc284d0f34edd1ad5db631d1c8a6593e769468eac2f6db300d7f779c" as const;
export const HOST_CREDENTIAL_SCOPE = "full-daemon-operator" as const;
export const HOST_CAPABILITIES = [
  "executionWorkspace.createManaged",
  "executionWorkspace.observe",
  "executionWorkspace.archive",
  "taskAgent.createWithInitialPrompt",
  "reviewerAgent.createWithInitialPrompt",
  "helperAgent.observe",
  "agent.observe",
  "agent.archive",
] as const;

export type HostCapability = (typeof HOST_CAPABILITIES)[number];

export interface HostDescriptor {
  credentialScope: typeof HOST_CREDENTIAL_SCOPE;
  contractVersion: typeof HOST_CONTRACT_VERSION;
  contractHash: typeof HOST_CONTRACT_SHA256;
  capabilities: typeof HOST_CAPABILITIES;
}

export interface HostCommand {
  requestId: string;
  idempotencyKey: string;
  expectedVersion: number;
  capability: HostCapability;
  arguments: Readonly<Record<string, unknown>>;
}

export interface HostObservation {
  requestId: string;
  cursor: number;
  observedAt: string;
  result: unknown;
}

export interface DirectorHost {
  describe(): Promise<HostDescriptor>;
  invoke(command: HostCommand): Promise<HostObservation>;
}

export class HostHandshakeError extends Error {
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "HostHandshakeError";
    this.code = code;
  }
}

export const EXPECTED_HOST_DESCRIPTOR: HostDescriptor = Object.freeze({
  credentialScope: HOST_CREDENTIAL_SCOPE,
  contractVersion: HOST_CONTRACT_VERSION,
  contractHash: HOST_CONTRACT_SHA256,
  capabilities: HOST_CAPABILITIES,
});

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

export function assertHostDescriptor(value: unknown): HostDescriptor {
  if (!isRecord(value)) {
    throw new HostHandshakeError("HOST_DESCRIPTOR_REQUIRED", "host descriptor is required");
  }
  const keys = Object.keys(value).sort();
  const expectedKeys = ["capabilities", "contractHash", "contractVersion", "credentialScope"];
  if (keys.length !== expectedKeys.length || keys.some((key, index) => key !== expectedKeys[index])) {
    throw new HostHandshakeError("HOST_DESCRIPTOR_FIELDS", "host descriptor fields do not match");
  }
  if (value.credentialScope !== HOST_CREDENTIAL_SCOPE) {
    throw new HostHandshakeError("HOST_CREDENTIAL_SCOPE", "host credential scope does not match");
  }
  if (value.contractVersion !== HOST_CONTRACT_VERSION) {
    throw new HostHandshakeError("HOST_CONTRACT_VERSION", "host contract version does not match");
  }
  if (value.contractHash !== HOST_CONTRACT_SHA256) {
    throw new HostHandshakeError("HOST_CONTRACT_HASH", "host contract hash does not match");
  }
  if (!Array.isArray(value.capabilities)) {
    throw new HostHandshakeError("HOST_CAPABILITIES", "host capabilities are required");
  }
  if (
    value.capabilities.length !== HOST_CAPABILITIES.length ||
    value.capabilities.some((capability, index) => capability !== HOST_CAPABILITIES[index])
  ) {
    throw new HostHandshakeError("HOST_CAPABILITIES", "host capability set does not match");
  }
  return value as unknown as HostDescriptor;
}
